robin_stocks/helper.py
I think it would be great if we can expect the output dicts are in the same order as the inputSymbols.
Thanks for launching robin_stocks!
=> keep original order of inputSymbols

robin_stocks/account.py, robin_stocks/authentication.py, robin_stocks/helper.py, robin_stocks/options.py, robin_stocks/orders.py, robin_stocks/profiles.py
The first fix is adding a decorator to let users know when they are calling a method that requires them to be logged in and prints a readable error message if it is violated.
The second fix addresses an issue I found with my sparse test account which will crash if build_holdings() is called without any holdings.  Rather than returning empty (correct) it previously threw an exception.
=> Add informative messages for logged-in methods and fix a bug with sparse accounts

robin_stocks/__init__.py, robin_stocks/orders.py, robin_stocks/urls.py
Open orders current API provides only stocks but NOT option's.
This contains the fix.
=> get all open option orders

robin_stocks/authentication.py
When robin_stocks is used as a library, the cached credentials are saved in a pickle file inside `site-packages`, which seems non-intuitive and also pollutes `site-packages` if the library is later uninstalled (pickle file and directory structure left behind by default).
This change saves the cached credential pickle file into the user's home folder (regardless of OS) under a hidden `.tokens` directory instead.
=> moving credentials file to home folder

robin_stocks/authentication.py
This change allows a user to call `login()` with no arguments at all. If credentials cache exists, the login proceeds normally (using cached token), otherwise the user is prompted to enter username/password from the command-line
=> do not require username/password if cred cache exists

robin_stocks/stocks.py
When multiple symbols are requested and if some of them don't exist on Robinhood, the result just simply omit the symbols. It's not possible to know what exact symbols are missed, because request / result are just lists, no way to match them. By adding _symbol_ property to stock result, it can easily figure out what symbols are valid ones.
=> Adding symbol property to Stock result

robin_stocks/orders.py
Also when you buy fractions which equate to less than <$1.00 in RH may fail occasionally. Needs an helper which computes least possible fractional quantity before sending the order.
@jmfernandes How do you get average stock price from the stock_info? Would be useful to compute fractions on avg price for volatile stocks and that appears to be RH implementation as well.
=> Fixed selling fractional only at 6 decimals and <= 1.00 to <1.00

robin_stocks/stocks.py
Add an option for users to set the interval when calling `get_historicals`
Addresses issue #126
=> Add parameter for historicals to specify interval

robin_stocks/account.py, robin_stocks/urls.py
As mentioned in the following issue: https://github.com/jmfernandes/robin_stocks/issues/134
It was not possible to query custom watchlist information. This pull request fixes the problem with an updated url syntax and query to get custom list data.
=> Added new url syntax for getting watchlists

examples/get_accurate_gains.py, robin_stocks/account.py, robin_stocks/authentication.py, setup.py
In the get_total_dividends() method, when we check each item in data, we simply use item['account'] in the sum. However, that can result in over-counting in the case where you have transactions with 'voided' state. There could be other such states, and hence the safest way is to only include states that are known to be yielding the right dividend transactions, i.e 'paid' and 'reinvested'.
=> Fix dividend calculation

robin_stocks/__init__.py, robin_stocks/markets.py, robin_stocks/urls.py, setup.py
Hey started playing with this yesterday, wanted to pull Robin Hood Top Movers data. Realized `get_top_movers()` was pulling from the S&P endpoint.
I updated `get_top_movers()` so it pulls from the `/midlands/tags/tag/top-movers/` API, which matches the Top Movers data that Robin Hood displays. I moved the old `get_top_movers()` into `get_top_movers_sp500()` so the old functionality is available for anyone who wants it.
=> Update get_top_movers functionality

robin_stocks/__init__.py, robin_stocks/account.py, robin_stocks/authentication.py, robin_stocks/crypto.py, robin_stocks/globals.py, robin_stocks/helper.py, robin_stocks/markets.py, robin_stocks/options.py, robin_stocks/orders.py, robin_stocks/stocks.py
This goes with Issue #119 - I had free time today, so I put together
and option on how to do it.
Rather than always outputting to stdout, I added a new set_output
and get_output in helper.py that allows the client to set the stream
that all print statements will go to.  It defaults to stdout so the
standard behavior should remain unchanged.
Rather than pass this around everywhere, I made the stream a global.
I stayed with the default print() function and just passed in the
stream with the file= keyword.  It may have made more sense to create
a new print function wrapper. So that the file= logic is in one place
The other controversial part is the write_spinner function.  I did the
simple approach to do the spinner only if the output is equal to stdout.
Otherwise the spinner is ignored.  I …
=> Allow the print() output to go to anywhere

robin_stocks/crypto.py
Fixes #203
Makes the docs reflect the actual return values for the `get_crypto_quote` and `get_crypto_quote_by_id` functions (they appear to have been copied from possibly `get_crypto_info`.
=> get_crypto_quote* functions had incorrect docstrings

robin_stocks/options.py
find_options_by_specific_profitability will fail if an empty list is returned by get_option_market_data_by_id. Added a check for empty list.
=> Fixed find_options_by_specific_profitability

robin_stocks/robinhood/orders.py
Every once in a while, I'll get errors like this:
```
Error in request_post: HTTPSConnectionPool(host='nummus.robinhood.com', port=443): Read timed out. (read timeout=16)
```
I'm hoping retrying the request a few times will be enough to have it go through. If this isn't the desired fix, then `ref_id` needs to be a param we can control so we can write our own retry logic.
=> Make crypto orders more reliable

robin_stocks/robinhood/orders.py, tests/test_robinhood.py
fix flooring of order quantity value in the case of fractional shares
add test for find_stock_orders() changes
[issue](https://github.com/jmfernandes/robin_stocks/issues/339)
#339
=> Fix incidental quantity flooring 

robin_stocks/robinhood/stocks.py
Added caching to three helper functions in stocks module using `cache` decorator from `functools`. These function return a fixed value for a given input. When exporting stocks info they may get called hundreds of times, most of which may be repeated calls for the same stock. Below is timings for export calls for my Robinhood account before (33.4s) and after (6.61s) caching. Similar times observed in multiple runs.
~This test~ Below run only involves `get_symbol_by_url` call. Tests are not changed as test calls to functions wrapped with caching exist.
```
/Documents/GitHub/robin_stocks (master) » ipython                                                                                                          ahmet@Merves-MacBook-Pro
Python 3.9.9 (main, Dec 29 2021, 15:49:43)
Type …
```
=> Caching constant output of stocks helper functions.

robin_stocks/robinhood/orders.py, setup.py
Updated the order_buy_fractional_by_price() function to incorporate changes by @scurt8 to accommodate Robinhood's new order form format. This was causing a "Your app version is missing important stock trading updates. You can still place orders on the web." response from Robinhood when submitting an order for fractional shares.
=> order_buy_fractional_by_price Patch

robin_stocks/robinhood/options.py, robin_stocks/robinhood/orders.py, robin_stocks/robinhood/urls.py
-- add check if instrument is None in get_option_market_data_by_id()
-- add account_number to get_all_open_option_orders()
-- add account_number to option_orders_url()
=> bug fix, and add account_number (for IRA account)

robin_stocks/robinhood/orders.py
When using the package I noticed that the order of the parameters for certain orders was not correct. The original code would pass the accountNumber argument as the limit price in certain cases which is not intended behavior. I fixed the order of the parameters to insure that limit prices are correct passed to the base order method.
=> Fixed account number parameter in order method

robin_stocks/robinhood/profiles.py, robin_stocks/robinhood/urls.py
I created this to solve the issue I was facing here (https://github.com/jmfernandes/robin_stocks/issues/426). The main issue was that there was no way to retrieve the Robinhood IRA account numbers, despite support for IRAs being added earlier when passing the account number into certain functions (such as `load_account_profile`).
At first, I considered creating a new function to serve this purpose (which is still an option), but I found that it could be accomplished in a simpler manner using the already existing `load_account_profile` function. Before, this function was hardcoded to always return the first item in the data list (the `indexzero` option). This means that only the data for the first account is returned (the individual account) unless the IRA number is hardcoded and passed in …
=> Allow Get All Account Profile Info (Including IRA Numbers)

robin_stocks/robinhood/authentication.py, setup.py
This is a small PR that allows a user to choose where to save the robinhood cookies `.pickle` file. If not specified, it defaults to `~/.tokens/` (the current behavior). When defined with an absolute or relative path, it uses that instead.
=> Add support for Custom Pickle Paths

robin_stocks/robinhood/export.py, robin_stocks/robinhood/orders.py
This is a minimal change that allows users to specify the account number when exporting stock orders. This resolves part of #366.
=> Account number optional argument for `export_completed_stock_orders`, `get_all_stock_orders`

robin_stocks/robinhood/account.py, robin_stocks/robinhood/urls.py
Adds a function to get unified transfers. From what I can tell this is currently the only way to get debit/credit transfer info which is how I stumbled across it (trying to calculate total contributions). From what I can tell there is no endpoint similar to `/ach/transfers` or `/wire/transfers` for card related transfers. 
Nevertheless, this PR adds a way to get all transfer types in a single request. The url was found via network tab in browser when viewing `https://robinhood.com/account/transfers` which is how they probably populate the 'Completed Transfers' area of the page.
Example json output with redacted values:
```
[
{
"id": "REDACTED",
"originating_account_id": "REDACTED",
"originating_account_type": "rhs_account",
"originating_user_uuid": "REDACTED",
"receiving_account_id": …
```
=> Unified transfers

robin_stocks/robinhood/orders.py, robin_stocks/robinhood/urls.py, setup.py
Hello, and I'm excited to submit my first pull request. I have discovered that by adding a parameter of `updated_at[gte]=start_date` request URL via the arguments for `option_orders_url()` and `orders_url()`, it is possible to limit the order request by start date, proportionally speeding up the time required to receive a short list of orders. 
I have tested with pytest and confirmed that the results are in an independent test. Results with two different dates are attached. 
If you have any feedback or notes on my contribution process, I would be grateful to know if I submitted everything correctly or not.
=> All orders start date parameter

robin_stocks/robinhood/authentication.py, setup.py
Fixes robin_stocks.authentication.login() to prompt for an mfa_code if needed during login.
=> alternate fix for #524 - mfa_login requirement in _validate_sherrif_id
